name: Build and Cross-browser Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cross-browser-test:
    runs-on: macos-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge, safari]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: oracle

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B -q -DskipTests package

      - name: Set up browser dependencies for ${{ matrix.browser }}
        run: |
          if [ "${{ matrix.browser }}" = "chrome" ]; then
            brew install --cask google-chrome
          elif [ "${{ matrix.browser }}" = "firefox" ]; then
            brew install --cask firefox
          elif [ "${{ matrix.browser }}" = "edge" ]; then
            brew install --cask microsoft-edge
          elif [ "${{ matrix.browser }}" = "safari" ]; then
            echo "Safari is pre-installed on macOS"
          fi

      - name: Run local tests on ${{ matrix.browser }}
        run: |
          if [ "${{ matrix.browser }}" = "safari" ]; then
            mvn -B -q test -Pweb-execution -Dsuite=local -Dtarget=local -Dbrowser=safari
          else
            mvn -B -q test -Pweb-execution -Dsuite=local -Dtarget=local -Dheadless=true -Dbrowser=${{ matrix.browser }}
          fi

#name: Build and Test
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
#jobs:
#  local-test:
#    runs-on: macos-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          java-version: 22
#          distribution: oracle
#
#      - name: Cache Maven packages
#        uses: actions/cache@v4
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#
#      - name: Build with Maven
#        run: mvn -B -q -DskipTests package
#
#      - name: Run local tests
#        run: mvn -B -q test -Pweb-execution -Dsuite=local -Dtarget=local -Dheadless=false -Dbrowser=safari
